export const DEMO_USERS = [
  {
    id: "1",
    email: "admin@example.com",
    password: "admin123",
    name: "Admin User",
    role: "admin" as const,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=admin",
  },
  {
    id: "2",
    email: "manager@example.com",
    password: "manager123",
    name: "Manager User",
    role: "manager" as const,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=manager",
  },
  {
    id: "3",
    email: "user@example.com",
    password: "user123",
    name: "Regular User",
    role: "user" as const,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=user",
  },
]

export const DEMO_USERS_DATA = [
  { id: "1", name: "John Doe", email: "john@example.com", role: "Admin", status: "Active", joinDate: "2024-01-15" },
  { id: "2", name: "Jane Smith", email: "jane@example.com", role: "Manager", status: "Active", joinDate: "2024-02-20" },
  { id: "3", name: "Bob Johnson", email: "bob@example.com", role: "User", status: "Inactive", joinDate: "2024-03-10" },
  { id: "4", name: "Alice Brown", email: "alice@example.com", role: "User", status: "Active", joinDate: "2024-01-25" },
  {
    id: "5",
    name: "Charlie Wilson",
    email: "charlie@example.com",
    role: "Manager",
    status: "Active",
    joinDate: "2024-02-14",
  },
  {
    id: "6",
    name: "Diana Martinez",
    email: "diana@example.com",
    role: "User",
    status: "Active",
    joinDate: "2024-03-05",
  },
  {
    id: "7",
    name: "Edward Davis",
    email: "edward@example.com",
    role: "User",
    status: "Inactive",
    joinDate: "2024-01-30",
  },
  {
    id: "8",
    name: "Fiona Garcia",
    email: "fiona@example.com",
    role: "Admin",
    status: "Active",
    joinDate: "2024-02-28",
  },
  {
    id: "9",
    name: "George Rodriguez",
    email: "george@example.com",
    role: "User",
    status: "Active",
    joinDate: "2024-03-12",
  },
  {
    id: "10",
    name: "Hannah Lee",
    email: "hannah@example.com",
    role: "Manager",
    status: "Active",
    joinDate: "2024-01-20",
  },
  {
    id: "11",
    name: "Isaac Taylor",
    email: "isaac@example.com",
    role: "User",
    status: "Active",
    joinDate: "2024-02-08",
  },
  {
    id: "12",
    name: "Julia Anderson",
    email: "julia@example.com",
    role: "User",
    status: "Inactive",
    joinDate: "2024-03-01",
  },
]

export const SIDEBAR_ITEMS = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: "LayoutDashboard",
    href: "/dashboard",
    roles: ["admin", "manager", "user"],
  },
  { id: "users", label: "Users", icon: "Users", href: "/dashboard/users", roles: ["admin", "manager"] },
  { id: "analytics", label: "Analytics", icon: "BarChart3", href: "/dashboard/analytics", roles: ["admin", "manager"] },
  { id: "reports", label: "Reports", icon: "FileText", href: "/dashboard/reports", roles: ["admin", "manager"] },
  { id: "settings", label: "Settings", icon: "Settings", href: "/dashboard/settings", roles: ["admin"] },
  { id: "profile", label: "Profile", icon: "User", href: "/dashboard/profile", roles: ["admin", "manager", "user"] },
]
